# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sample_poisson <- function(y, X, n0, m_mix_orig, v_mix_orig, w_mix_orig, log_offset, S_beta, beta_init, niter, pr, thin) {
    .Call(`_SamplerPoisson_sample_poisson`, y, X, n0, m_mix_orig, v_mix_orig, w_mix_orig, log_offset, S_beta, beta_init, niter, pr, thin)
}

sample_poisson_MH <- function(y, X, n0, m_mix_orig, v_mix_orig, w_mix_orig, m_mix_adj, v_mix_adj, w_mix_adj, check_mix, b_gibbs_start, b_check, adjust, log_offset, S_beta, beta_init, niter, pr, thin) {
    .Call(`_SamplerPoisson_sample_poisson_MH`, y, X, n0, m_mix_orig, v_mix_orig, w_mix_orig, m_mix_adj, v_mix_adj, w_mix_adj, check_mix, b_gibbs_start, b_check, adjust, log_offset, S_beta, beta_init, niter, pr, thin)
}

sample_poisson_auto <- function(y, X, n0, m_mix_orig, v_mix_orig, w_mix_orig, m_mix_adj, v_mix_adj, w_mix_adj, check_mix_min, check_mix_max, b_gibbs_start, b_check, threshold_MH, threshold_adj, log_offset, S_beta, beta_init, niter, pr, thin) {
    .Call(`_SamplerPoisson_sample_poisson_auto`, y, X, n0, m_mix_orig, v_mix_orig, w_mix_orig, m_mix_adj, v_mix_adj, w_mix_adj, check_mix_min, check_mix_max, b_gibbs_start, b_check, threshold_MH, threshold_adj, log_offset, S_beta, beta_init, niter, pr, thin)
}

sample_poissonm_nob <- function(y, n0, MH, a_pri, b_pri, X, Z_list, K_list, m_mix_orig, v_mix_orig, w_mix_orig, m_mix_adj, v_mix_adj, w_mix_adj, check_mix, b_check, adjust, b_gibbs_start, log_offset, rank_K_g, A_list, e_list, S_beta, beta_init, g_init_list, S2g_init, niter, pr, thin) {
    .Call(`_SamplerPoisson_sample_poissonm_nob`, y, n0, MH, a_pri, b_pri, X, Z_list, K_list, m_mix_orig, v_mix_orig, w_mix_orig, m_mix_adj, v_mix_adj, w_mix_adj, check_mix, b_check, adjust, b_gibbs_start, log_offset, rank_K_g, A_list, e_list, S_beta, beta_init, g_init_list, S2g_init, niter, pr, thin)
}

sample_poissonm_nob_auto <- function(y, n0, a_pri, b_pri, X, Z_list, K_list, m_mix_orig, v_mix_orig, w_mix_orig, m_mix_adj, v_mix_adj, w_mix_adj, check_mix_min, check_mix_max, b_gibbs_start, b_check, threshold_MH, threshold_adj, log_offset, rank_K_g, A_list, e_list, S_beta, beta_init, g_init_list, S2g_init, niter, pr, thin) {
    .Call(`_SamplerPoisson_sample_poissonm_nob_auto`, y, n0, a_pri, b_pri, X, Z_list, K_list, m_mix_orig, v_mix_orig, w_mix_orig, m_mix_adj, v_mix_adj, w_mix_adj, check_mix_min, check_mix_max, b_gibbs_start, b_check, threshold_MH, threshold_adj, log_offset, rank_K_g, A_list, e_list, S_beta, beta_init, g_init_list, S2g_init, niter, pr, thin)
}

